# Generated by Django 4.1.7 on 2023-05-08 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('cuisine_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedRestaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('restaurantname', models.CharField(max_length=45)),
                ('comment', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'scrapping',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
