# Generated by Django 4.1.7 on 2023-05-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_scrapedrestaurant_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
